adding awkcel, hawk, and wzcat

diff --git a/libwayne/bin/hawk b/libwayne/bin/hawk
--- a/libwayne/bin/hawk
+++ b/libwayne/bin/hawk
@@ -39,7 +39,7 @@ else
     else # kill -l has the format of space-separated "HUP INT QUIT", etc...
 	kill -l | newlines | grep -v IOT | nl   # but note IOT is a duplicate of TRAP--both are signal 6
     fi | head -20 | egrep -i "$IGNORE" | awk '128+$1=='"$STATUS{good=1}END{exit !good}" && exit 0
-    echo "gawk failed with status $STATUS program file is in directory $TMP" >&2
+    echo "gawk failed with status $STATUS program file is in file $TMP" >&2
     trap "" 0 1 2 3 15 # do not remove file
     exit $STATUS
 fi
